name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 2.0.0
homepage: https://github.com/mmcc007/tool_mobile
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  tool_base: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: 4.1.0
